### PR TITLE
Issue 22

### PR DESCRIPTION
**Pull request by jarhun88**
Modularized AreaCharts into its own separate Component called Charts.jsx, if there are any suggestions for changes, let me know. Hoping to start data transmission once approved...

### CODE REVIEW

**Comment by aviquez96** [comment]
Hey John, nice work! Some things to change though, if you see the google docs, we want the charts to be 2 per row, so if you could adjust that before I approve the pr. Also, if you could add text for the axis, just to represent what each axis means that would be great (don't worry about the units for now). Lastly, just to remind you that the temperature chart has 2 curves, and the power has 1 curve, so if you could adjust this plz. This also applies for the history tab.

**Comment by febg** [comment]
Hey Look great just found a bug that we might as well fix it sooner but the graphs are not being scales correctly when the window size changes

screen shot 2018-10-30 at 10 30 06 pm

**Comment by jluisfgarza** [comment]
I'm fixing some stuff and deleting code that's not used. I'll make a push in a min

**Comment by jluisfgarza** [comment]
image
I made some UI tweaks and formatted some code. Also exported some variables that were not exported on mainStyle.jsx @jarhun88  check @aviquez96 's comments.

This is the charts library we are using: http://recharts.org/en-US/ and the UI component library: https://material-ui.com/customization/overrides/ p

Please let me know I you update dependencies to use new functionality (I may break the code in some cases but if you find utility on updating to a newer version we could do it)

**Pull request merged**
