### PR TITLE
Reboot of this app

### PR DESCRIPTION
**Pull request by lcfyi**
Howdy folks,

I've redesigned portions of this app such that it's no longer an Electron app; instead, it's a web app hosted on Firebase. In doing so, we get to reap the benefit of faster deployments, and.. that's about it, actually.

Most of the front-end has been reused, but I did make some optimizations here and there to take out unnecessary code. Some notable changes are:
- Auth is now handled by Firebase, rather than local storage
- We are able to get sensor data updates from Firebase
- The config page is mostly complete; this is mostly to change the user's settings but there will probably be some sensor changes, going forward

For now, this PR is still quite incomplete. I have a roadmap that includes:
- Data upload options
- Better data display
- Some additional refactoring to remove legacy code
- Better documentation w.r.t. the use of Firebase, and the flow of the app
- Testing pipeline

For now, you can see the current iteration here: https://sustaingineering-horus.web.app/

I was originally thinking of rebasing the app completely and spinning it off into another, but I don't think that's the most optimal option, given that there's already been a lot of work done by you guys. 

Let me know what you guys think.

### CODE REVIEW

**Comment by jluisfgarza** [comment]
Looks good to me! What do you guys think about forking this repo to another one for the web app only? (Just for the sake of keeping the electron app for future reference) Also, how about turning the firebase web app into a PWA for better experience on mobile devices as well as enabling notifications?

**Comment by lcfyi** [comment]
Sure, that's also an option. I wanted the repo to sit in the Sustaingineeringubc org, hence why I submitted the PR. 

I was thinking about that approach as well; my original reasoning against that was that I didn't think we'd necessarily benefit from making it a PWA (other than maybe cached components loading faster) since all the data is centralized anyway; without an internet connection, things won't work. Notifications is an interesting angle that I didn't think of, though. I'll add that to the list of stretch goals to explore. 

If you have read/write access to the org, could you add me as a contributor?

**Comment by jluisfgarza** [comment]
Sure, @aviquez96 or @febg could you help us adding @lcfyi as a contributor (I currently don't  have admin access to the organization)

**Comment by jluisfgarza** [comment]
@lcfyi I already created a new repo and sent you an invite: https://github.com/Sustaingineeringubc/Horus-Web-App

It is a clone of this one, I believe that if you change the remote URL you would be able to push your changes. Although you will still need to wait for an invite to the organization from one of the admins to appear as a member.

**Comment by lcfyi** [comment]
Cheers, I just accepted the invite. It should work exactly as you described; I'll change my origin and push when I get home tonight.

**Pull request closed without merging**
